project:
  type: website
  preview:
    port: 4200

website:
  title: "Julia for Engineering Students"
  # author: "Dr. Torsten Schenkel"
  # affiliation: "Department of Engineering and Mathematics, Sheffield Hallam University"
  # date: "03/04/2023"
  sidebar:
    contents:
      - section: "Home"
        contents:
        - intro.qmd
        - juliaFeatures.qmd
      - section: "Basics"
        contents:
          - juliaBasics.qmd
          - installingJulia.qmd
          - basicSyntax.qmd
          - comparisonMatlab.qmd
          - tricks.qmd
      - section: "Examples"
        contents:
          # - examples.qmd
  #     menu:
          - ODEsolver.qmd
  #   - references.qmd
  # # appendices:
  #   - resources.qmd

  # downloads:
  #   - epub
  #   - pdf

  # license: CC-BY-4.0
  # page-footer:
  #     - text: "About"
  #       href: about.qmd
  #     - text: "License"
  #       href: license.qmd

bibliography: references.bib

date-format: long
papersize: a4

filters:
  - quarto
  - noteout-write-notebooks
  - include-code-files

format:
  html:
    cap-location: margin
    reference-location: margin
    citation-location: margin
    theme:
      light: sandstone
      dark: darkly
    html-math-method: mathjax
    comments:
      hypothesis: true
  pdf:
    include-in-header:
      text: |
        \usepackage{amsmath, amssymb}
    cap-location: margin
    reference-location: margin
    citation-location: margin
    documentclass: scrreprt
  epub:
    html-math-method: mathml

noteout:
  nb-format: ipynb

jupyter: julia-1.9
keep-ipynb: true

execute:
  cache: true
  daemon: 3600
  freeze: auto
